### ISSUE TITLE
explain/show/link to search use case

### ISSUE THREAD

**Issue by afeld** [18F/jekyll_pages_api#12]
* In code: https://github.com/18F/hub/pull/80
* In practice: https://18f.gsa.gov/hub/

**Comment by tomjohnson1492** [comment]
There's a great use case for this plugin if you're creating context-sensitive help for an application. Most technical writers like to keep control of the help text rather than surrendering it to the actual code of an application (which then locks the text into release-window-only updates.) I wrote a post about how to leverage this plugin for context sensitive help here: [Creating context-sensitive help by converting your help into a JSON API with Jekyll](http://bit.ly/jekylljsonapi).

**Comment by afeld** [comment]
Yay @tomjohnson1492!

https://github.com/tomjohnson1492/jekyllwithlunr

**Comment by afeld** [comment]
Taken care of by https://github.com/18F/jekyll_pages_api_search.
