### ISSUE TITLE
How to avoid problematic characters such as â€™ in converted json?

### ISSUE THREAD

**Issue by tomjohnson1492** [18F/jekyll_pages_api#16]
Do you know how to avoid characters that get munged in the conversion, such as a curly apostrophe in "user's" getting converted to userâ€™s?

**Comment by afeld** [comment]
Some encoding issue, and _who the hell knows_ how to fix _that_. :football: :runner:

**Comment by tomjohnson1492** [comment]
I can find all curly quotes and replace them straight quotes. I'm not even sure where the curly stuff came from, honestly. 

One thing I'm unsure about is how to grab links. If the page has a link like this:

```
<a href="http://google.com">google.com</a>
```

When the pages become json, all that carries over is `google.com` unless I use character codes for the angle brackets. How can I pass all of the HTML tags through JSON?

**Comment by afeld** [comment]
The original use case for this plugin was to support search, so I very intentionally [stripped out HTML](https://github.com/18F/jekyll_pages_api/blob/4c3b121066e3a594598d40b0a724b094efe338db/lib/jekyll_pages_api/filters.rb#L23). If you need the markup, I'd say to follow the `url` and request the pages themselves.

**Comment by afeld** [comment]
@tomjohnson1492 I don't think there's an encoding issue for this gem... just added a test in #18. Looked into your particular issue a bit, and it seems that your HTML might be invalid:

---

![screen shot 2015-02-10 at 11 50 15 pm](https://cloud.githubusercontent.com/assets/86842/6142372/459196d6-b183-11e4-9569-891f5342710d.png)

---

*http://idratherbewriting.com/wp-content/apidemos/docasapi/about/*

Not sure if this was intentional, to test it? Not sure where that's getting converted to invalid(?) characters in this gem, but not sure what the ideal result would be, either. I understand very little about encoding anyway, so would love advice from anyone that stumbles upon this thread.
